# Generated by Django 2.0.4 on 2018-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='GameMoves',
            new_name='GameMove',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
