# Generated by Django 2.0.4 on 2018-04-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180426_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameName',
            field=models.CharField(default='Game #<built-in function id>', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='testapp.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondPlayerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondPlayer', to='testapp.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='testapp.Player'),
        ),
        migrations.AlterField(
            model_name='gamemove',
            name='gameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='testapp.Game'),
        ),
    ]
