# Generated by Django 2.0.4 on 2018-04-26 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20180426_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.AlterField(
            model_name='game',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
