# Generated by Django 2.0.4 on 2018-05-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20180426_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ownerScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='secondPlayerScore',
            field=models.IntegerField(default=0),
        ),
    ]
