# Generated by Django 2.0.4 on 2018-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20180510_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemove',
            name='ownerMove',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gamemove',
            name='secondPlayerMove',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
